language: node_js
env:
  - FORCE_COLOR=true
notifications:
  email: false
node_js:
  - 10.14
  - 12
  - node
install: yarn install
script:
  - yarn validate
  - npx codecov@3
branches:
  only:
    - master
    - beta

jobs:
  include:
    - stage: release
      node_js: 12
      script: kcd-scripts travis-release
